on:
    workflow_dispatch:
      inputs:
        test_files:
          description: "Enter pytest marker (e.g., smoke, regression)"
          required: true
          default: "api_tests"
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
  
        - run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python -m playwright install --with-deps
  
        - name: Run marked tests
          run: |
            if [ -z "${{ github.event.inputs.marker }}" ]; then
              pytest --maxfail=1 --disable-warnings -v
            else
              pytest -m ${{ github.event.inputs.marker }} --maxfail=1 --disable-warnings -v
            fi
  